// ─── Mock data for XYLO Demo ─────────────────────────────────────────────────
// Realistic Apple store data — iPhone models, sales, users, dashboard stats

export const users = [
  { id: 1, name: "Nahuel G.",  email: "nahuel@xylobox.store",  role: "admin" },
  { id: 2, name: "Carlos V.",  email: "carlos@xylobox.store",  role: "user"  },
  { id: 3, name: "Andrés R.",  email: "andres@xylobox.store",  role: "user"  },
];

export const exchangeRate = {
  id: 1,
  source_name: "Manual",
  buy_rate_ars: 1045,
  sell_rate_ars: 1065,
  is_active: true,
  manual_override: true,
  manual_buy_rate_ars: 1045,
  manual_sell_rate_ars: 1065,
  updated_at: "2026-04-02T10:30:00",
};

export const exchangeRates = [exchangeRate];

// ─── Products in stock (in_stock) ────────────────────────────────────────────
const stockProducts = [
  {
    id: 1,
    model: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Natural Titanium",
    imei: "359876543218765",
    serial_number: "F2LXQ3Y8KX",
    battery_health: 97,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Usado A+",
    purchase_price_usd: 980,
    suggested_sale_price_usd: 1200,
    photo_url: null,
    status: "in_stock",
    sim_type: "eSIM + Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: null,
  },
  {
    id: 2,
    model: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Black Titanium",
    imei: "359876543219876",
    serial_number: "F2LXQ3Y9MN",
    battery_health: 95,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 970,
    suggested_sale_price_usd: 1190,
    photo_url: null,
    status: "in_stock",
    sim_type: "eSIM + Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: null,
  },
  {
    id: 3,
    model: "iPhone 15 Pro",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Natural Titanium",
    imei: "359765432187654",
    serial_number: "F2KPQ1R7YH",
    battery_health: 100,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Nuevo",
    purchase_price_usd: 850,
    suggested_sale_price_usd: 1050,
    photo_url: null,
    status: "in_stock",
    sim_type: "eSIM + Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: "Sellado de fábrica",
  },
  {
    id: 4,
    model: "iPhone 15",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Pink",
    imei: "358765432198765",
    serial_number: "F1KMQ8T5PL",
    battery_health: 98,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Nuevo",
    purchase_price_usd: 720,
    suggested_sale_price_usd: 890,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Importación directa",
    created_by: 2,
    notes: null,
  },
  {
    id: 5,
    model: "iPhone 15",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Black",
    imei: "358765432109876",
    serial_number: "F1KNQ9U6RM",
    battery_health: 96,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Usado A+",
    purchase_price_usd: 690,
    suggested_sale_price_usd: 850,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Carlos - reventa",
    created_by: 2,
    notes: null,
  },
  {
    id: 6,
    model: "iPhone 14 Pro",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Space Black",
    imei: "357654321876543",
    serial_number: "F0HJP4S3NK",
    battery_health: 88,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 680,
    suggested_sale_price_usd: 850,
    photo_url: null,
    status: "in_stock",
    sim_type: "eSIM + Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: null,
  },
  {
    id: 7,
    model: "iPhone 14 Pro",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Silver",
    imei: "357654321987654",
    serial_number: "F0HJP5T4ML",
    battery_health: 85,
    cosmetic_condition: "Bueno",
    functional_condition: "Excelente",
    condition_type: "Usado B",
    purchase_price_usd: 650,
    suggested_sale_price_usd: 820,
    photo_url: null,
    status: "in_stock",
    sim_type: "eSIM + Nano SIM",
    supplier: "Permuta cliente",
    created_by: 3,
    notes: "Scratches mínimos en esquinas",
  },
  {
    id: 8,
    model: "iPhone 14",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Midnight",
    imei: "356543218765432",
    serial_number: "FZGJN2R8PK",
    battery_health: 91,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Usado A+",
    purchase_price_usd: 540,
    suggested_sale_price_usd: 680,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Importación directa",
    created_by: 2,
    notes: null,
  },
  {
    id: 9,
    model: "iPhone 14",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Blue",
    imei: "356543219876543",
    serial_number: "FZGJN3S9QL",
    battery_health: 87,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 510,
    suggested_sale_price_usd: 650,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Permuta cliente",
    created_by: 3,
    notes: null,
  },
  {
    id: 10,
    model: "iPhone 14",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Purple",
    imei: "356543210987654",
    serial_number: "FZGJN4T0RM",
    battery_health: 84,
    cosmetic_condition: "Bueno",
    functional_condition: "Excelente",
    condition_type: "Usado B",
    purchase_price_usd: 500,
    suggested_sale_price_usd: 640,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Carlos - reventa",
    created_by: 2,
    notes: null,
  },
  {
    id: 11,
    model: "iPhone 13 Pro",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Sierra Blue",
    imei: "354321876543218",
    serial_number: "FYEJM1Q7OK",
    battery_health: 79,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 420,
    suggested_sale_price_usd: 540,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: null,
  },
  {
    id: 12,
    model: "iPhone 13",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Midnight",
    imei: "354321987654329",
    serial_number: "FYEJM2R8PL",
    battery_health: 82,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 380,
    suggested_sale_price_usd: 480,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Permuta cliente",
    created_by: 3,
    notes: null,
  },
  {
    id: 13,
    model: "iPhone 13",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Starlight",
    imei: "354321098765430",
    serial_number: "FYEJM3S9QM",
    battery_health: 76,
    cosmetic_condition: "Bueno",
    functional_condition: "Excelente",
    condition_type: "Usado B",
    purchase_price_usd: 350,
    suggested_sale_price_usd: 450,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Carlos - reventa",
    created_by: 2,
    notes: null,
  },
  {
    id: 14,
    model: "iPhone 13 mini",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Pink",
    imei: "354321198765431",
    serial_number: "FYEJM4T0RN",
    battery_health: 80,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 310,
    suggested_sale_price_usd: 400,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Permuta cliente",
    created_by: 3,
    notes: null,
  },
  {
    id: 15,
    model: "iPhone 12",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Black",
    imei: "352198765432109",
    serial_number: "FXDIL9P6NK",
    battery_health: 73,
    cosmetic_condition: "Bueno",
    functional_condition: "Excelente",
    condition_type: "Usado B",
    purchase_price_usd: 280,
    suggested_sale_price_usd: 370,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: null,
  },
  {
    id: 16,
    model: "iPhone 12",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "White",
    imei: "352198765432200",
    serial_number: "FXDIL0Q7OL",
    battery_health: 71,
    cosmetic_condition: "Regular",
    functional_condition: "Muy bueno",
    condition_type: "Usado C",
    purchase_price_usd: 260,
    suggested_sale_price_usd: 350,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Carlos - reventa",
    created_by: 2,
    notes: "Vidrio trasero con micro rayones",
  },
  {
    id: 17,
    model: "iPhone 12 mini",
    brand: "Apple",
    category: "iPhone",
    storage: "64GB",
    color: "PRODUCT RED",
    imei: "352198765432311",
    serial_number: "FXDIL1R8PM",
    battery_health: 68,
    cosmetic_condition: "Bueno",
    functional_condition: "Excelente",
    condition_type: "Usado B",
    purchase_price_usd: 220,
    suggested_sale_price_usd: 300,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Permuta cliente",
    created_by: 3,
    notes: null,
  },
  {
    id: 18,
    model: "iPhone 11",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Black",
    imei: "351098765432198",
    serial_number: "FWCHK7O4MJ",
    battery_health: 85,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 180,
    suggested_sale_price_usd: 240,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Carlos - reventa",
    created_by: 2,
    notes: null,
  },
  {
    id: 19,
    model: "iPhone 11",
    brand: "Apple",
    category: "iPhone",
    storage: "64GB",
    color: "White",
    imei: "351098765432209",
    serial_number: "FWCHK8P5NK",
    battery_health: 80,
    cosmetic_condition: "Bueno",
    functional_condition: "Excelente",
    condition_type: "Usado B",
    purchase_price_usd: 160,
    suggested_sale_price_usd: 220,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Permuta cliente",
    created_by: 3,
    notes: null,
  },
  {
    id: 20,
    model: "iPhone SE (3ª gen)",
    brand: "Apple",
    category: "iPhone",
    storage: "128GB",
    color: "Midnight",
    imei: "350987654321987",
    serial_number: "FVBGJ6N3LI",
    battery_health: 92,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Nuevo",
    purchase_price_usd: 280,
    suggested_sale_price_usd: 360,
    photo_url: null,
    status: "in_stock",
    sim_type: "Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: "Caja sellada",
  },
];

// ─── Sold products (status: "sold") ──────────────────────────────────────────
const soldProducts = [
  {
    id: 101,
    model: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "iPhone",
    storage: "512GB",
    color: "White Titanium",
    imei: "359876540011111",
    serial_number: "F2LXQ3Z9AB",
    battery_health: 100,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Nuevo",
    purchase_price_usd: 1050,
    suggested_sale_price_usd: 1280,
    photo_url: null,
    status: "sold",
    sim_type: "eSIM + Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: null,
  },
  {
    id: 102,
    model: "iPhone 14 Pro",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Deep Purple",
    imei: "357654320022222",
    serial_number: "F0HJP4T5BC",
    battery_health: 92,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Usado A+",
    purchase_price_usd: 700,
    suggested_sale_price_usd: 880,
    photo_url: null,
    status: "sold",
    sim_type: "eSIM + Nano SIM",
    supplier: "Importación directa",
    created_by: 2,
    notes: null,
  },
  {
    id: 103,
    model: "iPhone 13 Pro Max",
    brand: "Apple",
    category: "iPhone",
    storage: "256GB",
    color: "Alpine Green",
    imei: "354321870033333",
    serial_number: "FYEJM3U1CD",
    battery_health: 84,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 480,
    suggested_sale_price_usd: 600,
    photo_url: null,
    status: "sold",
    sim_type: "Nano SIM",
    supplier: "Carlos - reventa",
    created_by: 3,
    notes: null,
  },
  {
    id: 104,
    model: "iPhone 14",
    brand: "Apple",
    category: "iPhone",
    storage: "512GB",
    color: "Starlight",
    imei: "356543210044444",
    serial_number: "FZGJN5V2DE",
    battery_health: 90,
    cosmetic_condition: "Muy bueno",
    functional_condition: "Excelente",
    condition_type: "Usado A",
    purchase_price_usd: 560,
    suggested_sale_price_usd: 710,
    photo_url: null,
    status: "sold",
    sim_type: "Nano SIM",
    supplier: "Permuta cliente",
    created_by: 2,
    notes: null,
  },
  {
    id: 105,
    model: "iPhone 15",
    brand: "Apple",
    category: "iPhone",
    storage: "512GB",
    color: "Yellow",
    imei: "358765430055555",
    serial_number: "F1KMQ9W3EF",
    battery_health: 99,
    cosmetic_condition: "Impecable",
    functional_condition: "Excelente",
    condition_type: "Nuevo",
    purchase_price_usd: 760,
    suggested_sale_price_usd: 950,
    photo_url: null,
    status: "sold",
    sim_type: "Nano SIM",
    supplier: "Importación directa",
    created_by: 1,
    notes: null,
  },
];

export const products = [...stockProducts, ...soldProducts];

// ─── Sales ────────────────────────────────────────────────────────────────────
export const sales = [
  {
    id: 1,
    product_id: 101,
    seller_id: 2,
    sale_price_usd: 1280,
    purchase_price_usd_snapshot: 1050,
    gross_profit_usd: 230,
    client_name: "Juan García",
    sale_date: "2026-04-02T14:22:00",
    notes: null,
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 1, method: "transferencia", amount_usd: 1280, reference: "CVU: 0123456", created_at: "2026-04-02T14:22:00" },
    ],
  },
  {
    id: 2,
    product_id: 102,
    seller_id: 3,
    sale_price_usd: 880,
    purchase_price_usd_snapshot: 700,
    gross_profit_usd: 180,
    client_name: "Marcos López",
    sale_date: "2026-04-01T11:05:00",
    notes: null,
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 2, method: "efectivo", amount_usd: 500, reference: null, created_at: "2026-04-01T11:05:00" },
      { id: 3, method: "transferencia", amount_usd: 380, reference: "MP: #48291", created_at: "2026-04-01T11:05:00" },
    ],
  },
  {
    id: 3,
    product_id: 105,
    seller_id: 2,
    sale_price_usd: 950,
    purchase_price_usd_snapshot: 760,
    gross_profit_usd: 190,
    client_name: "Paula Rodríguez",
    sale_date: "2026-04-01T09:48:00",
    notes: "Cliente frecuente",
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 4, method: "cripto", amount_usd: 950, reference: "USDT TRC20: TF9kx…", created_at: "2026-04-01T09:48:00" },
    ],
  },
  {
    id: 4,
    product_id: 103,
    seller_id: 3,
    sale_price_usd: 600,
    purchase_price_usd_snapshot: 480,
    gross_profit_usd: 120,
    client_name: "Sebastián Martínez",
    sale_date: "2026-03-31T16:30:00",
    notes: null,
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 5, method: "transferencia", amount_usd: 600, reference: "CVU: 9876543", created_at: "2026-03-31T16:30:00" },
    ],
  },
  {
    id: 5,
    product_id: 104,
    seller_id: 2,
    sale_price_usd: 710,
    purchase_price_usd_snapshot: 560,
    gross_profit_usd: 150,
    client_name: "Diego González",
    sale_date: "2026-03-30T13:15:00",
    notes: null,
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 6, method: "efectivo", amount_usd: 710, reference: null, created_at: "2026-03-30T13:15:00" },
    ],
  },
  {
    id: 6,
    product_id: 101,
    seller_id: 3,
    sale_price_usd: 1150,
    purchase_price_usd_snapshot: 940,
    gross_profit_usd: 210,
    client_name: "Valentina Torres",
    sale_date: "2026-03-28T10:00:00",
    notes: null,
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 7, method: "cripto", amount_usd: 600, reference: "USDT: 0xAb3…", created_at: "2026-03-28T10:00:00" },
      { id: 8, method: "transferencia", amount_usd: 550, reference: "CVU: 1122334", created_at: "2026-03-28T10:00:00" },
    ],
  },
  {
    id: 7,
    product_id: 102,
    seller_id: 2,
    sale_price_usd: 840,
    purchase_price_usd_snapshot: 670,
    gross_profit_usd: 170,
    client_name: "Lucía Fernández",
    sale_date: "2026-03-25T15:45:00",
    notes: null,
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 9, method: "transferencia", amount_usd: 840, reference: "MP: #58302", created_at: "2026-03-25T15:45:00" },
    ],
  },
  {
    id: 8,
    product_id: 103,
    seller_id: 3,
    sale_price_usd: 580,
    purchase_price_usd_snapshot: 460,
    gross_profit_usd: 120,
    client_name: "Rodrigo Álvarez",
    sale_date: "2026-03-22T12:20:00",
    notes: null,
    status: "completed",
    has_trade_in: false,
    trade_in_value_usd: null,
    has_deposit: false,
    deposit_amount_usd: null,
    remaining_balance_usd: null,
    payments: [
      { id: 10, method: "efectivo", amount_usd: 580, reference: null, created_at: "2026-03-22T12:20:00" },
    ],
  },
];

// ─── Dashboard summary ────────────────────────────────────────────────────────
export const dashboardSummary = {
  sales_this_month_value_usd: 3110,
  sales_last_month_value_usd: 2290,
  profit_this_month_usd: 600,
  profit_last_month_usd: 440,
  sales_this_month_count: 3,
  sales_last_month_count: 5,
  total_stock_value_usd: 31600,
  total_products_in_stock: 20,
  total_gross_profit_usd: 1840,
  total_sales_count: 8,
};

// ─── Top models ───────────────────────────────────────────────────────────────
export const topModels = [
  { model: "iPhone 15 Pro Max", sales_count: 2, total_sales_usd: 2230 },
  { model: "iPhone 14 Pro",     sales_count: 2, total_sales_usd: 1720 },
  { model: "iPhone 15",         sales_count: 2, total_sales_usd: 1660 },
  { model: "iPhone 13 Pro Max", sales_count: 2, total_sales_usd: 1180 },
  { model: "iPhone 14",         sales_count: 1, total_sales_usd:  710 },
];

// ─── Payment methods ──────────────────────────────────────────────────────────
export const paymentMethods = [
  { method: "transferencia", count: 5, total_usd: 3550 },
  { method: "cripto",        count: 2, total_usd: 1550 },
  { method: "efectivo",      count: 3, total_usd: 1290 },
];

// ─── Monthly stats (last 6 months) ────────────────────────────────────────────
export const monthlyStats = [
  { label: "Nov 25", cost_usd: 5200,  profit_usd: 980,  revenue_usd: 6180  },
  { label: "Dic 25", cost_usd: 6800,  profit_usd: 1320, revenue_usd: 8120  },
  { label: "Ene 26", cost_usd: 5900,  profit_usd: 1080, revenue_usd: 6980  },
  { label: "Feb 26", cost_usd: 7400,  profit_usd: 1540, revenue_usd: 8940  },
  { label: "Mar 26", cost_usd: 2510,  profit_usd: 440,  revenue_usd: 2950  },
  { label: "Abr 26", cost_usd: 2510,  profit_usd: 600,  revenue_usd: 3110  },
];

// ─── Recent sales (last 5) ────────────────────────────────────────────────────
export const recentSales = [
  { id: 1, model: "iPhone 15 Pro Max 512GB", client_name: "Juan García",     sale_date: "2026-04-02T14:22:00", sale_price_usd: 1280, gross_profit_usd: 230 },
  { id: 2, model: "iPhone 14 Pro 256GB",     client_name: "Marcos López",    sale_date: "2026-04-01T11:05:00", sale_price_usd:  880, gross_profit_usd: 180 },
  { id: 3, model: "iPhone 15 512GB",         client_name: "Paula Rodríguez", sale_date: "2026-04-01T09:48:00", sale_price_usd:  950, gross_profit_usd: 190 },
  { id: 4, model: "iPhone 13 Pro Max 256GB", client_name: "Sebastián M.",    sale_date: "2026-03-31T16:30:00", sale_price_usd:  600, gross_profit_usd: 120 },
  { id: 5, model: "iPhone 14 512GB",         client_name: "Diego González",  sale_date: "2026-03-30T13:15:00", sale_price_usd:  710, gross_profit_usd: 150 },
];
